blank_issues_enabled: false
contact_links:
  - name: ðŸ’¡ Feature Request
    url: https://github.com/enrique-lozano/Monekin/discussions/categories/ideas
    about: Share your ideas about new features that you would like to see in the future
  - name: ðŸ’¬ Monekin community support
    url: https://github.com/enrique-lozano/Monekin/discussions/categories/q-a
    about: Get help or advice on how to use the application
